In [68]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import warnings

In [69]:
df = pd.read_excel('Final Feature SER.xlsx')

In [70]:
df.head()

Path  label   roll_of_30  \
0  Acted Emotional Speech Dynamic Database/fear/f...      0   861.696844   
1  Acted Emotional Speech Dynamic Database/fear/f...      0   882.633865   
2  Acted Emotional Speech Dynamic Database/fear/f...      0   975.761719   
3  Acted Emotional Speech Dynamic Database/fear/f...      0  1205.622746   
4  Acted Emotional Speech Dynamic Database/fear/f...      0  1071.758942   

    roll_of_50   roll_of_70   roll_of_90           sc      pitch   contrast  \
0  1472.664611  2661.341670  5464.640244  2255.163755  20.725584  74.953849   
1  1774.062981  3164.471006  6562.546937  2613.362624  26.604160  75.946830   
2  1743.235840  2916.703125  5331.928711  2360.061152  26.549549  74.698857   
3  1942.484225  2984.123347  5483.039739  2509.701460  15.810717  60.172080   
4  1966.029654  3298.356423  5946.217278  2667.367217  21.201275  85.566494   

   flatness  ...  croma_var_4  croma_var_5  croma_var_6  croma_var_7  \
0  0.015859  ...     0.069918     0.094098     0.103631     0.082798   
1  0.016071  ...     0.124383     0.106709     0.134793     0.123825   
2  0.027758  ...     0.099596     0.097517     0.094142     0.108840   
3  0.019989  ...     0.088697     0.088577     0.131554     0.118669   
4  0.016265  ...     0.044568     0.015855     0.008668     0.017240   

   croma_var_8  croma_var_9  croma_var_10  croma_var_11  croma_var_12  \
0     0.057802     0.079231      0.089020      0.120973      0.106051   
1     0.152942     0.064132      0.051390      0.040874      0.058504   
2     0.094250     0.087771      0.101411      0.108509      0.115968   
3     0.125060     0.113986      0.034199      0.030645      0.038538   
4     0.036811     0.114330      0.105673      0.131539      0.137840   

   croma_var_13  
0      0.141908  
1      0.101552  
2      0.112361  
3      0.117547  
4      0.099415  

[5 rows x 106 columns]

In [71]:
Y =df['label']

In [72]:
X =(df[df.columns[2:]]).values

In [73]:
type(X)

numpy.ndarray

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=123,test_size=0.2)

In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
clf_n = LogisticRegression(penalty='l2',max_iter=10000,tol=0.001,)
clf_n.fit(X_train,Y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=10000, tol=0.001)

In [77]:
clf_n.score(X_test,Y_test)

0.7603305785123967

In [78]:
clf_n.score(X_train,Y_train)

0.772256728778468

In [79]:
from sklearn.metrics import classification_report,confusion_matrix
predict = clf_n.predict(X_test)
print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       0.58      0.75      0.65        20
           1       0.93      0.93      0.93        28
           2       0.76      0.72      0.74        18
           3       0.84      0.76      0.80        34
           4       0.63      0.57      0.60        21

    accuracy                           0.76       121
   macro avg       0.75      0.75      0.74       121
weighted avg       0.77      0.76      0.76       121



In [80]:
print(confusion_matrix(Y_test,predict))


[[15  0  0  0  5]
 [ 1 26  0  1  0]
 [ 1  0 13  2  2]
 [ 4  0  4 26  0]
 [ 5  2  0  2 12]]


In [81]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier

In [82]:
pipe = make_pipeline(StandardScaler(), SGDClassifier(penalty='l2',max_iter=1000,
                                                     alpha=0.00001,learning_rate='optimal',n_iter_no_change=15,                                                  random_state=123,early_stopping=True))
pipe.fit(X_train,Y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier',
                 SGDClassifier(alpha=1e-05, early_stopping=True,
                               n_iter_no_change=15, random_state=123))])

In [83]:
print(pipe.score(X_train,Y_train))
print(pipe.score(X_test,Y_test))

0.7971014492753623
0.7520661157024794


In [84]:
from sklearn.metrics import classification_report,confusion_matrix
predict = pipe.predict(X_test)
print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       0.67      0.50      0.57        20
           1       0.84      0.96      0.90        28
           2       0.65      0.72      0.68        18
           3       0.80      0.82      0.81        34
           4       0.68      0.62      0.65        21

    accuracy                           0.75       121
   macro avg       0.73      0.73      0.72       121
weighted avg       0.75      0.75      0.75       121



In [85]:
pipe = make_pipeline(StandardScaler(), SGDClassifier(loss='log',penalty='l2',max_iter=1000,
                                                     alpha=0.01,learning_rate='optimal',n_iter_no_change=15,
                                                     random_state=123,early_stopping=True,tol=0.001))
pipe.fit(X_train,Y_train)
print(pipe.score(X_train,Y_train))
print(pipe.score(X_test,Y_test))


0.8178053830227743
0.7603305785123967


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py:173: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(


In [86]:
from sklearn.metrics import classification_report,confusion_matrix
predict = pipe.predict(X_test)
print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       0.68      0.65      0.67        20
           1       0.96      0.89      0.93        28
           2       0.59      0.72      0.65        18
           3       0.89      0.74      0.81        34
           4       0.62      0.76      0.68        21

    accuracy                           0.76       121
   macro avg       0.75      0.75      0.75       121
weighted avg       0.78      0.76      0.77       121



In [87]:
print(confusion_matrix(Y_test,predict))

[[13  1  1  0  5]
 [ 1 25  0  0  2]
 [ 1  0 13  2  2]
 [ 1  0  7 25  1]
 [ 3  0  1  1 16]]


In [88]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
tr = DecisionTreeClassifier(criterion="gini",max_depth=8,min_samples_split=4,min_samples_leaf=20)
pipe = make_pipeline(StandardScaler(), tr)
pipe.fit(X_train,Y_train)
print(pipe.score(X_train,Y_train))
print(pipe.score(X_test,Y_test))

0.629399585921325
0.5041322314049587


In [89]:
from sklearn.metrics import classification_report,confusion_matrix
predict = pipe.predict(X_test)
print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       0.32      0.35      0.33        20
           1       0.66      0.75      0.70        28
           2       0.43      0.33      0.38        18
           3       0.70      0.47      0.56        34
           4       0.37      0.52      0.43        21

    accuracy                           0.50       121
   macro avg       0.49      0.49      0.48       121
weighted avg       0.53      0.50      0.51       121



In [90]:
from sklearn.ensemble import RandomForestClassifier

In [91]:
rf = RandomForestClassifier(n_estimators=55,criterion='entropy',max_depth=7,
                            min_impurity_decrease=0.001,max_leaf_nodes=8,random_state=12)
pipe = make_pipeline(StandardScaler(), rf)
pipe.fit(X_train,Y_train)
print(pipe.score(X_train,Y_train))
print(pipe.score(X_test,Y_test))

0.6915113871635611
0.6033057851239669


In [92]:
from sklearn.metrics import classification_report,confusion_matrix
predict = pipe.predict(X_test)
print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       0.43      0.30      0.35        20
           1       0.68      0.93      0.79        28
           2       0.40      0.44      0.42        18
           3       0.67      0.65      0.66        34
           4       0.69      0.52      0.59        21

    accuracy                           0.60       121
   macro avg       0.57      0.57      0.56       121
weighted avg       0.60      0.60      0.59       121



In [93]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(20,),activation='relu',solver='lbfgs',alpha=1e-05,learning_rate_init=0.00001,
                   max_iter=500,early_stopping=False,validation_fraction=0.1,batch_size=64,
                    learning_rate='constant',momentum=0.9)
pipe = make_pipeline(StandardScaler(), mlp)
pipe.fit(X_train,Y_train)
print(pipe.score(X_train,Y_train))
print(pipe.score(X_test,Y_test))

1.0
0.7355371900826446


In [94]:
from sklearn.metrics import classification_report,confusion_matrix
predict = pipe.predict(X_test)
print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       0.52      0.60      0.56        20
           1       0.93      0.96      0.95        28
           2       0.57      0.67      0.62        18
           3       0.88      0.82      0.85        34
           4       0.62      0.48      0.54        21

    accuracy                           0.74       121
   macro avg       0.70      0.71      0.70       121
weighted avg       0.74      0.74      0.74       121



In [95]:
print(confusion_matrix(Y_test,predict))

[[12  2  2  0  4]
 [ 1 27  0  0  0]
 [ 2  0 12  3  1]
 [ 0  0  5 28  1]
 [ 8  0  2  1 10]]


In [96]:
#SVM

In [97]:
from sklearn.svm import SVC

In [98]:
svm = SVC(C=0.6, kernel='poly', degree=3, gamma='scale', coef0=0.491, shrinking=True, probability=True, 
          tol=0.001, cache_size=400, class_weight='balanced', verbose=False, max_iter=1000, decision_function_shape='ovo', 
          break_ties=False, random_state=123)
pipe = make_pipeline(StandardScaler(), svm)
pipe.fit(X_train,Y_train)
print('Training Accuracy: ',pipe.score(X_train,Y_train)*100)
print('Testing Accuracy: ',pipe.score(X_test,Y_test)*100)

Training Accuracy:  92.96066252587993
Testing Accuracy:  76.03305785123968


In [99]:
from sklearn.metrics import classification_report,confusion_matrix
predict = pipe.predict(X_test)
print(classification_report(Y_test,predict))

              precision    recall  f1-score   support

           0       0.55      0.55      0.55        20
           1       0.87      0.93      0.90        28
           2       0.79      0.83      0.81        18
           3       0.85      0.85      0.85        34
           4       0.61      0.52      0.56        21

    accuracy                           0.76       121
   macro avg       0.73      0.74      0.73       121
weighted avg       0.75      0.76      0.76       121



In [100]:
print(confusion_matrix(Y_test,predict))

[[11  2  0  2  5]
 [ 1 26  0  0  1]
 [ 1  0 15  2  0]
 [ 2  0  2 29  1]
 [ 5  2  2  1 11]]


In [101]:
#Naive Bayes

In [102]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB(var_smoothing=.9)
pipe_nb = make_pipeline(StandardScaler(), gnb)
pipe_nb.fit(X_train,Y_train)
print('Training Accuracy: ',pipe_nb.score(X_train,Y_train)*100)
print('Testing Accuracy: ',pipe_nb.score(X_test,Y_test)*100)

Training Accuracy:  54.24430641821946
Testing Accuracy:  47.107438016528924


In [103]:
from sklearn.metrics import classification_report,confusion_matrix
predict = pipe_nb.predict(X_test)
print(classification_report(Y_test,predict))


              precision    recall  f1-score   support

           0       0.43      0.30      0.35        20
           1       0.58      0.79      0.67        28
           2       0.30      0.17      0.21        18
           3       0.77      0.29      0.43        34
           4       0.35      0.76      0.48        21

    accuracy                           0.47       121
   macro avg       0.48      0.46      0.43       121
weighted avg       0.53      0.47      0.45       121

